### PR TITLE
 Adding DVL.msg  && Adding dvl_serial.cpp node

### PR DESCRIPTION
**Pull request by MoMagDii**
Done adding the dvl_serial [c++] node to the sensors pkg
DOne adding the DVL.msg to the custom_ros_interfaces pkg

### CODE REVIEW

**Comment by MoMagDii** [comment]
There is a typo in the readme file in the sensors pkg  :
$ ros2 run dvl_interface dvl               || should be >> ||     $ ros2 run sensors dvl

**Comment by MoMagDii** [comment]
[Done] Reformatting the source code and passing colcon test  
image
[Done] Updating the sensors/README file 
[In progress]  adding more tests and exceptions inside the parser class 
[In progress]  Detecting the USB port number connected to the DVL automatically instead of using a default number 
[In Progress] Adding more comments inside the source code

**Comment by IbrahimHabibV** [comment]
@MoMagDii  the branch has conflicts you should solve it first

**Comment by MoMagDii** [comment]
@IbrahimHabibV Done solving the branch conflicts.

**Comment by MoMagDii** [comment]
There is an "XMLLINT"  test-error in the custom_ros_interfaces/package.xml file , resolving this test issue is in progress

**Comment by MoMagDii** [comment]
@IbrahimHabibV  done  editing the README file &&  adding a capability to pass the USB port name as an argument for the dvl_serial.cpp node

**Pull request closed without merging**
